[tool.pylint.main]
load-plugins = ["pylint.extensions.docparams"]
jobs = 0
persistent = true

[tool.pylint.messages_control]
disable = [
    "too-few-public-methods",
    "logging-fstring-interpolation",
    "missing-module-docstring",
    "invalid-name",
    "line-too-long"
]

[tool.pylint.format]
max-line-length = 100
max-module-lines = 1000
indent-string = "    "

[tool.pylint.design]
max-args = 6
max-locals = 15
max-returns = 6
max-branches = 12
max-statements = 50
max-parents = 7
max-attributes = 7
min-public-methods = 2
max-public-methods = 20
max-bool-expr = 5

[tool.pylint.similarities]
min-similarity-lines = 4
ignore-comments = true
ignore-docstrings = true
ignore-imports = false

[tool.pylint.variables]
init-import = false
dummy-variables-rgx = "_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_"
additional-builtins = []
callbacks = ["cb_", "_cb"]

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_", "id", "db", "ok"]
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata"]
name-group = []
include-naming-hint = false
property-classes = ["abc.abstractproperty"]

[tool.pylint.string]
check-str-concat-over-line-jumps = false

[tool.pylint.imports]
deprecated-modules = ["optparse", "tkinter.tix"]
import-graph = []
ext-import-graph = []
int-import-graph = []
known-standard-library = []
known-third-party = ["enchant"]
analyse-fallback-blocks = false

[tool.pylint.classes]
defining-attr-methods = ["__init__", "__new__", "setUp", "__post_init__"]
valid-classmethod-first-arg = ["cls"]
valid-metaclass-classmethod-first-arg = ["cls"]
exclude-protected = ["_asdict", "_fields", "_replace", "_source", "_make"]

[tool.pylint.typecheck]
ignore-on-opaque-inference = true
ignore-mixin-members = true
ignored-modules = []
ignored-classes = ["optparse.Values", "thread._local", "_thread._local"]
generated-members = []
contextmanager-decorators = ["contextlib.contextmanager"]
missing-member-hint = true
missing-member-hint-distance = 1
missing-member-max-choices = 1

[tool.pylint.spelling]
spelling-dict = ""
spelling-ignore-words = ""
spelling-private-dict-file = ""
spelling-store-unknown-words = false
max-spelling-suggestions = 4

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
ignore_missing_imports = true
strict_equality = true

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.bandit]
exclude_dirs = ["tests", "test_*.py", "*_test.py"]
skips = ["B101", "B601"]

[[tool.bandit.blacklist_calls]]
names = ["pickle.loads", "pickle.load", "pickle.Unpickler", "dill.loads", "shelve.open"]
message = "Pickle library appears to be in use, possible security issue."