name: 🛡️ Setup Branch Protection

on:
  workflow_dispatch:  # Ручной запуск
  push:
    branches: [main]
    paths: ['.github/workflows/branch-protection.yml']

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    if: github.repository == 'Abilka94/WoW-Reg-Legion-Bot'
    
    steps:
      - name: 🔐 Setup Branch Protection for main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: 'Abilka94',
                repo: 'WoW-Reg-Legion-Bot',
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: ['tests', 'security-scan', 'lint']
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 2,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true,
                lock_branch: false,
                allow_fork_syncing: true
              });
              console.log('✅ Branch protection for main configured successfully');
            } catch (error) {
              console.log('❌ Error configuring main branch protection:', error.message);
            }

      - name: 🧪 Setup Branch Protection for testing
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: 'Abilka94',
                repo: 'WoW-Reg-Legion-Bot',
                branch: 'testing',
                required_status_checks: {
                  strict: true,
                  contexts: ['tests', 'build']
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: false,
                lock_branch: false,
                allow_fork_syncing: true
              });
              console.log('✅ Branch protection for testing configured successfully');
            } catch (error) {
              console.log('❌ Error configuring testing branch protection:', error.message);
            }

      - name: 📚 Setup Branch Protection for legacy
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: 'Abilka94',
                repo: 'WoW-Reg-Legion-Bot',
                branch: 'legacy',
                required_status_checks: null,
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: false,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                allow_force_pushes: true,  # Разрешено для исторических исправлений
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: false,
                lock_branch: false,
                allow_fork_syncing: true
              });
              console.log('✅ Branch protection for legacy configured successfully');
            } catch (error) {
              console.log('❌ Error configuring legacy branch protection:', error.message);
            }

      - name: 📊 Summary
        run: |
          echo "🛡️ Branch Protection Setup Complete!"
          echo ""
          echo "✅ main branch:"
          echo "  - Requires 2 approving reviews"
          echo "  - Requires status checks: tests, security-scan, lint"
          echo "  - Dismisses stale reviews"
          echo "  - Requires conversation resolution"
          echo "  - Blocks direct pushes"
          echo ""
          echo "✅ testing branch:"
          echo "  - Requires 1 approving review"
          echo "  - Requires status checks: tests, build"
          echo "  - Dismisses stale reviews"
          echo "  - Blocks direct pushes"
          echo ""
          echo "✅ legacy branch:"
          echo "  - Requires 1 approving review"
          echo "  - Allows force pushes (for historical fixes)"
          echo "  - Less restrictive for maintenance"